services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y imagemagick
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
